-- 1. Reset: Drop existing tables if they exist (WARNING: This deletes all existing data!)
DROP TABLE IF EXISTS public.pla_flight_events;
DROP TABLE IF EXISTS public.pla_activity;

-- 2. Create the Main Activity Table (Announcement Level)
CREATE TABLE public.pla_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  activity_date DATE UNIQUE NOT NULL,  -- Ensure only one entry per day
  publish_date DATE,                   -- Announcement date
  link TEXT,                           -- Source URL
  aircraft_total INT DEFAULT 0,
  aircraft_crossing INT DEFAULT 0,
  vessels_total INT DEFAULT 0,
  official_ships_total INT DEFAULT 0,
  balloons_total INT DEFAULT 0,
  original_text TEXT,                  -- Cleaned news snippet
  image_file TEXT                      -- Filename of the saved image
);

-- 3. Create the Detailed Events Table (Flight Record Level)
CREATE TABLE public.pla_flight_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT REFERENCES public.pla_activity(id) ON DELETE CASCADE, -- Link to main table
  activity_date DATE,                  -- Redundant date for faster direct querying
  link TEXT,                           -- Redundant link for direct source tracing
  time_range TEXT,                     -- e.g., "0810-1245"
  aircraft_type TEXT,                  -- e.g., "Fighter", "UAV"
  count INT DEFAULT 0,
  details TEXT[]                       -- Array of tags, e.g., ["Crossed Median Line"]
);

-- 4. Set Up Row Level Security (RLS)
ALTER TABLE public.pla_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pla_flight_events ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Allow public read, allow API insert)
CREATE POLICY "Enable read access for all users" ON public.pla_activity FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.pla_flight_events FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.pla_activity FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert access for all users" ON public.pla_flight_events FOR INSERT WITH CHECK (true);

-- 6. Indices for performance
CREATE INDEX idx_pla_activity_date ON public.pla_activity(activity_date);
CREATE INDEX idx_pla_flight_events_date ON public.pla_flight_events(activity_date);
CREATE INDEX idx_pla_flight_events_type ON public.pla_flight_events(aircraft_type);
